local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 9.0
  static_map: true
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  transform_tolerance: 0.5
  unknown_cost_value: 100
  lethal_cost_threshold: 100
  mark_threshold: 100



