TrajectoryPlannerROS:
  max_vel_x: 0.20
  min_vel_x: 0.10
  max_vel_theta: 0.10
  min_in_place_vel_theta: 0.7
  min_in_place_rotational_vel: 0.2 #0.15 original 0.8
  max_rot_vel: 0.3
  min_rot_vel: 0.2

  sim_time: 5.0 #3.0
#  path_distance_bias: 0.2 #--0.5 #--0.3
#  goal_distance_bias: 0.2 #--0.3
 
  acc_lim_theta: 0.5
  acc_lim_x: 0.15
  acc_lim_y: 0.15
  visualize_potential: true
  cost_factor: 0.55
  neutral_cost: 66

  holonomic_robot: true

  meter_scoring: true
#  yaw_goal_tolerance: 1.0 #2.0
#  xy_goal_tolerance: 0.2
  publish_cost_grid: true
  sim_granularity: 0.05
  frequency: 4 #1
  dwa: true
#  vx_samples: 3 #3 
