obstacle_range: 3.0
raytrace_range: 3.5
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
#robot_radius: ir_of_robot
# all units in meters
#The footprint of the robot and associated padding
footprint: [[-0.40, -0.20], [-0.40, 0.20], [0.20, 0.20], [0.40, 0.0], [0.20, -0.20]]
footprint_padding: 0.23

robot_radius: 0.2 # distance a circular robot should be clear of the obstacle
inflation_radius: 0.55
cost_scaling_factor: 2.58
#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

lethal_cost_threshold: 100

obstacles_laser:
    observation_sources: laser_scan_sensor #point_cloud_sensor
# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
    laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
