teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: RosAria/cmd_vel
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.5
        offset: 0.0
      -
        axis: 0
        target: angular.z
        scale: -0.5

  run:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: RosAria/cmd_vel
    deadman_buttons: [4, 5]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
        offset: 0.0
      -
        axis: 0
        target: angular.z
        scale: -0.5

  stop_everything:
    type: action
    action_name: stop_joints
    buttons: [4, 5, 6, 7]

  stop:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: RosAria/cmd_vel
    deadman_buttons: [0, 2]
    message_value:
      -
        target: linear.x
        value: 0.0
      -
        target: angular.z
        value: 0.0
      -
        target: linear.y
        value: 0.0

  mode_tape:
    type: topic
    message_type: awc/awc_cmd
    topic_name: awc_mode
    deadman_buttons: [1]
    message_value:
      -
        target: mode
        value: 1

  mode_auto:
    type: topic
    message_type: awc/awc_cmd
    topic_name: awc_mode
    deadman_buttons: [2]
    message_value:
      -
        target: mode
        value: 3

  mode_stop:
    type: topic
    message_type: awc/awc_cmd
    topic_name: awc_mode
    deadman_buttons: [0]
    message_value:
      -
        target: mode
        value: 0




