local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 9.0
  publish_frequency: 3.0
  static_map: true
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  transform_tolerance: 0.5
  lethal_cost_threshold: 100
  plugins:
    - {name: static_layer,        type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
#    - {name: obstacle_layer,         type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
#    - {name: voxel,               type: "costmap_2d::VoxelLayer"}
#    - {name: social_layer,           type: "social_navigation_layers::ProxemicLayer"}
#    - {name: social_pass_layer,      type: "social_navigation_layers::PassingLayer"}
#    - {name: costmap_prohibition_layer,       type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"}


