TrajectoryPlannerROS: 
  max_vel_x: 0.30
  min_vel_x: 0.05
  max_vel_theta: 0.30
  min_in_place_vel_theta: 0.20
  min_in_place_rotational_vel: 0.2 #0.15 original 0.8
  max_rot_vel: 0.4
  min_rot_vel: 0.25

  sim_time: 5.0 #3.0
#  path_distance_bias: 0.2 #--0.5 #--0.3
#  goal_distance_bias: 0.2 #--0.3
 
  acc_lim_th: 0.01
  acc_lim_x: 0.01
  acc_lim_y: 0.0
  visualize_potential: true

  holonomic_robot: false

  meter_scoring: true
  yaw_goal_tolerance: 1.0 #2.0
  xy_goal_tolerance: 0.2
  publish_cost_grid: true
  sim_granularity: 0.025
  frequency: 5 #1
  dwa: true
  vx_samples: 3 #3 
  publish_cost_grid_pc: true
